general-options:
  # ===========================================================================
  # General control flags
  # ===========================================================================
  verbose: False
  dry_run: False
  symlink_only: False
  keep_metadata: False
  # ===========================================================================
  # Options related to extracting ISBNs from files and finding metadata by ISBN
  # ===========================================================================
  isbn_regex: (?<![0-9])(-?9-?7[789]-?)?((-?[0-9]-?){9}[0-9xX])(?![0-9])
  isbn_direct_grep_files: ^(text/(plain|xml|html)|application/xml)$
  isbn_ignored_files: ^(image/(gif|svg.+)|application/(x-shockwave-flash|CDFV2|vnd.ms-opentype|x-font-ttf|x-dosexec|vnd.ms-excel|x-java-applet)|audio/.+|video/.+)$
  isbn_grep_reorder_files: True
  isbn_grep_rf_scan_first: 400
  isbn_grep_rf_reverse_last: 50
  isbn_metadata_fetch_order: Goodreads,Amazon.com,Google,ISBNDB,WorldCat xISBN,OZON.ru
  # ===========================================================================
  # Options for OCR
  # ===========================================================================
  ocr_enabled: False
  ocr_only_first_last_pages: 7,3
  ocr_command: tesseract_wrapper
  # ===========================================================================
  # Options related to extracting and searching for non-ISBN metadata
  # ===========================================================================
  token_min_length: 3
  tokens_to_ignore: ebook|book|novel|series|ed(ition)?|vol(ume)?|${RE_YEAR}
  organize_without_isbn_sources: Goodreads,Amazon.com,Google
  # ===========================================================================
  # Options related to the input and output files
  # ===========================================================================
  output_filename_template: ${d[AUTHORS]// & /, } - ${d[SERIES]:+[${d[SERIES]}] - }${d[TITLE]/:/ -}${d[PUBLISHED]:+ (${d[PUBLISHED]%%-*})}${d[ISBN]:+ [${d[ISBN]}]}.${d[EXT]}
  output_metadata_extension: meta
  # ===========================================================================
  # Miscellaneous options
  # ===========================================================================
  disable_logging: False
  logging_conf_path: ""

organize-ebooks:
  # ===========================================================================
  # Specific options for organizing files
  # ===========================================================================
  ebook_folders: ~/test/ebooks/folderA, ~/test/ebooks/folderB
  corruption_check_only: False
  tested_archive_extensions: ^(7z|bz2|chm|arj|cab|gz|tgz|gzip|zip|rar|xz|tar|epub|docx|odt|ods|cbr|cbz|maff|iso)$
  organize_without_isbn: False
  without_isbn_ignore:
  pamphlet_included_files: \.(png|jpg|jpeg|gif|bmp|svg|csv|pptx?)$
  pamphlet_excluded_files: \.(chm|epub|cbr|cbz|mobi|lit|pdb)$
  pamphlet_max_pdf_pages: 50
  pamphlet_max_filesize_kib: 250
  # ===========================================================================
  # Output options
  # ===========================================================================
  output_folder: ""
  output_folder_uncertain: ""
  output_folder_corrupt: ""
  output_folder_pamphlets: ""

interactive-organizer:
  output_folders:
  quick_mode: False
  custom_move_base_dir:
  restore_original_base_dir:
  diacritic_difference_maskings:
  match_partial_words: False

find-isbns:
  isbn_ret_separator: "\n"

rename-calibre-library:
  output_folder: ""
  save_metadata: recreate

split-into-folders:
  output_folder: ""
  start_number: 0
  folder_pattern: "%05d000"
  files_per_folder: 1000
